Add reload flag and modify 'destructive' flag to 'action'
datacom-teracom/radvd pull request #4
Opened 2019-06-04 17:00 UTC by warrior-graph

Now the action flag manages creation and deletion
of interfaces.

2019-06-04 19:14 UTC, ferdinandoterada requested changes

2019-06-04 19:14 UTC, ferdinandoterada commented on interface.c
> +		return NULL;
não pode ser que dê problema no acesso pra quem chama:
radvd.c:1019
iface = update_iface(iface, cjson_interface);
...
radvd.c:1047
iface->AdvPrefixList = delete_iface_prefix_by_addr(iface->AdvPrefixList, addr6);

2019-06-04 19:14 UTC, ferdinandoterada commented on radvd.c
> +		if (cJSON_IsFalse(cjson_action_iface)) {
eu tinha entendido que o action indicaria criação, atualização e deleção. fica confuso com valores de Action True e Action False. Rever essa parte (Talvez do jeito que comentaram "action" : "DESTROY" ou "action" : "CREATE")

2019-06-04 19:14 UTC, ferdinandoterada commented on test/test_msg_delete_prefix.json
> -                "destructive": false,
como é delete não tem que ter action?

2019-06-04 19:14 UTC, ferdinandoterada commented on radvd.c
>  			if (!iface->AdvPrefixList) {
não corre o perigo de ser nulo?

2019-06-04 19:14 UTC, ferdinandoterada commented on radvd.c
>  				continue;
iface->AdvPrefixList nao corre o perigo de ser nulo?

2019-06-04 19:49 UTC, warrior-graph commented on test/test_msg_delete_prefix.json
> -                "destructive": false,
No prefix não tem action.

2019-06-04 19:52 UTC, warrior-graph commented on interface.c
> +		return NULL;
Antes de chamar o update é feita a checkagem se iface é nulo e logo em seguida retorna e não continua. Esse if é só mais uma garantia, mas não tem como "virar nulo" dentro do update, a não ser que já venha nulo.

2019-06-04 19:52 UTC, warrior-graph commented on radvd.c
> +		if (cJSON_IsFalse(cjson_action_iface)) {
Irei alterar.

2019-06-04 20:11 UTC, warrior-graph commented on radvd.c
>  			if (!iface->AdvPrefixList) {
Só se o malloc falhar. Como conversamos no Slack, fica decidido abortar e ser restartado.

2019-06-05 18:27 UTC, warrior-graph commented on radvd.c
>  				continue;
Só se o malloc falhar também.

2019-06-07 20:40 UTC, ferdinandoterada approved these changes

2019-06-07 20:40 UTC, merged